### ISSUE TITLE
It crash when I click the other option button

### ISSUE THREAD

**Issue by NancalaStarry** [KosmX/emotes-forge#2]
This is my crash report:
https://paste.ubuntu.com/p/QFb64Cc9Jh/

**Comment by KosmX** [comment]
If you are using Forge, you have to install cloth config manually.

**Comment by NancalaStarry** [comment]
It works! I'm sorry! I didn't notice! It's my fault. I'm so sorry to disturb you. 
In addition, I also completed your Chinese translation project in crowdIn.
(Please excuse my English)
